### ISSUE TITLE
Boo maven build fails on linux.

### ISSUE THREAD

**Issue by sureshg** [oneops/boo#30] opened 2017-05-23 23:25 UTC
## Env Setup
   * CentOS Linux release `7.3.1611` (Core)
   * Linux `3.10.0`-514.6.1.el7.x86_64 x86_64 x86_64 x86_64 GNU/Linux
   * Maven Version: `3.5.0`
   * java version `1.8.0_131`
     Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

```
$ git clone git clone https://github.com/oneops/boo.git
$ cd boo
$ mvn 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.121 s
[INFO] Finished at: 2017-05-23T23:11:34Z
[INFO] Final Memory: 22M/54M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project boo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /root/boo && /usr/java/jdk1.8.0_131/jre/bin/java -jar /root/boo/target/surefire/surefirebooter2789433366398601718.jar /root/boo/target/surefire/surefire1271606498477299456tmp /root/boo/target/surefire/surefire_01752200186586900254tmp
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by mosabua** [comment] 2017-05-24 03:18
Duplicate of https://github.com/oneops/boo/issues/5

**Closed by mosabua** 2017-05-24 03:18 UTC
